import { Routes, RouterModule, CanActivate } from '@angular/router';
import { Pages } from './pages.component';
import { ModuleWithProviders } from '@angular/core';
import { AuthGuard } from '../shared/auth-guard.service';
export const routes: Routes = [
{
    path: 'login',
    loadChildren: 'app/pages/login/login.module#LoginModule'
},
{
    path: 'register',
    loadChildren: 'app/pages/register/register.module#RegisterModule'
},
{
    path: 'forgot',
    loadChildren: 'app/pages/forgot/forgot.module#ForgotModule'
},
{
    path: 'change-password',
    loadChildren: 'app/pages/change-password/change-password.module#ChangePasswordModule', 
    canActivate: [AuthGuard]
},
{
    path: 'pages',
    component: Pages,
    children: [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', loadChildren: './dashboard/dashboard.module#DashboardModule' },
    { path: 'unauthorized', loadChildren: './unauthorized/unauthorized.module#UnauthorizedModule'},
    { path: 'abonos', loadChildren: './abonos/abonos.module#AbonosModule',
        canActivateChild: [AuthGuard] },
    { path: 'abonos/orden/:idorden', loadChildren: './abonos/abonos.module#AbonosModule'},
    { path: 'alertas', loadChildren: './alertas/alertas.module#AlertasModule',
        canActivateChild: [AuthGuard] },
    { path: 'alertas/empleado/:idempleado', loadChildren: './alertas/alertas.module#AlertasModule'},
    { path: 'alertas/tipoalerta/:idtipoalerta', loadChildren: './alertas/alertas.module#AlertasModule'},
    { path: 'archivos', loadChildren: './archivos/archivos.module#ArchivosModule',
        canActivateChild: [AuthGuard] },
    { path: 'archivos/ordentarea/:idordentarea', loadChildren: './archivos/archivos.module#ArchivosModule'},
    { path: 'areas', loadChildren: './areas/areas.module#AreasModule',
        canActivateChild: [AuthGuard] },
    { path: 'checkouts', loadChildren: './checkouts/checkouts.module#CheckoutsModule',
        canActivateChild: [AuthGuard] },
    { path: 'checkouts/checkoutestado/:idcheckoutestado', loadChildren: './checkouts/checkouts.module#CheckoutsModule'},
    { path: 'checkouts/empleado/:idempleado', loadChildren: './checkouts/checkouts.module#CheckoutsModule'},
    { path: 'checkoutestados', loadChildren: './checkoutestados/checkoutestados.module#CheckoutestadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'ciudads', loadChildren: './ciudads/ciudads.module#CiudadsModule',
        canActivateChild: [AuthGuard] },
    { path: 'clientes', loadChildren: './clientes/clientes.module#ClientesModule',
        canActivateChild: [AuthGuard] },
    { path: 'clientes/persona/:idpersona', loadChildren: './clientes/clientes.module#ClientesModule'},
    { path: 'conceptos', loadChildren: './conceptos/conceptos.module#ConceptosModule',
        canActivateChild: [AuthGuard] },
    { path: 'egresoconceptos', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule',
        canActivateChild: [AuthGuard] },
    { path: 'egresoconceptos/concepto/:idconcepto', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule'},
    { path: 'egresoconceptos/empleado/:idempleado', loadChildren: './egresoconceptos/egresoconceptos.module#EgresoconceptosModule'},
    { path: 'empleados', loadChildren: './empleados/empleados.module#EmpleadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'empleados/area/:idarea', loadChildren: './empleados/empleados.module#EmpleadosModule'},
    { path: 'empleados/persona/:idpersona', loadChildren: './empleados/empleados.module#EmpleadosModule'},
    { path: 'empleados/si_user/:idsi_user', loadChildren: './empleados/empleados.module#EmpleadosModule'},
    { path: 'empleadotareas', loadChildren: './empleadotareas/empleadotareas.module#EmpleadotareasModule',
        canActivateChild: [AuthGuard] },
    { path: 'empleadotareas/empleado/:idempleado', loadChildren: './empleadotareas/empleadotareas.module#EmpleadotareasModule'},
    { path: 'empleadotareas/ordentarea/:idordentarea', loadChildren: './empleadotareas/empleadotareas.module#EmpleadotareasModule'},
    { path: 'empleadotareaestados', loadChildren: './empleadotareaestados/empleadotareaestados.module#EmpleadotareaestadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'empleadotareaestados/empleadotarea/:idempleadotarea', loadChildren: './empleadotareaestados/empleadotareaestados.module#EmpleadotareaestadosModule'},
    { path: 'empleadotareaestados/estadoscrum/:idestadoscrum', loadChildren: './empleadotareaestados/empleadotareaestados.module#EmpleadotareaestadosModule'},
    { path: 'estados', loadChildren: './estados/estados.module#EstadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'estadoscrums', loadChildren: './estadoscrums/estadoscrums.module#EstadoscrumsModule',
        canActivateChild: [AuthGuard] },
    { path: 'formulas', loadChildren: './formulas/formulas.module#FormulasModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordens', loadChildren: './ordens/ordens.module#OrdensModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordens/cliente/:idcliente', loadChildren: './ordens/ordens.module#OrdensModule'},
    { path: 'ordenestados', loadChildren: './ordenestados/ordenestados.module#OrdenestadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordenestados/estado/:idestado', loadChildren: './ordenestados/ordenestados.module#OrdenestadosModule'},
    { path: 'ordenestados/orden/:idorden', loadChildren: './ordenestados/ordenestados.module#OrdenestadosModule'},
    { path: 'ordenproductos', loadChildren: './ordenproductos/ordenproductos.module#OrdenproductosModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordenproductos/orden/:idorden', loadChildren: './ordenproductos/ordenproductos.module#OrdenproductosModule'},
    { path: 'ordenproductos/producto/:idproducto', loadChildren: './ordenproductos/ordenproductos.module#OrdenproductosModule'},
    { path: 'ordenproductos/tipoprecio/:idtipoprecio', loadChildren: './ordenproductos/ordenproductos.module#OrdenproductosModule'},
    { path: 'ordentareas', loadChildren: './ordentareas/ordentareas.module#OrdentareasModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordentareas/tarea/:idtarea', loadChildren: './ordentareas/ordentareas.module#OrdentareasModule'},
    { path: 'ordentareas/ordenproducto/:idordenproducto', loadChildren: './ordentareas/ordentareas.module#OrdentareasModule'},
    { path: 'ordentareaestados', loadChildren: './ordentareaestados/ordentareaestados.module#OrdentareaestadosModule',
        canActivateChild: [AuthGuard] },
    { path: 'ordentareaestados/estadoscrum/:idestadoscrum', loadChildren: './ordentareaestados/ordentareaestados.module#OrdentareaestadosModule'},
    { path: 'ordentareaestados/ordentarea/:idordentarea', loadChildren: './ordentareaestados/ordentareaestados.module#OrdentareaestadosModule'},
    { path: 'personas', loadChildren: './personas/personas.module#PersonasModule',
        canActivateChild: [AuthGuard] },
    { path: 'personas/ciudad/:idciudad', loadChildren: './personas/personas.module#PersonasModule'},
    { path: 'personas/sexo/:idsexo', loadChildren: './personas/personas.module#PersonasModule'},
    { path: 'productos', loadChildren: './productos/productos.module#ProductosModule',
        canActivateChild: [AuthGuard] },
    { path: 'productos/area/:idarea', loadChildren: './productos/productos.module#ProductosModule'},
    { path: 'productos/formula/:idformula', loadChildren: './productos/productos.module#ProductosModule'},
    { path: 'salidastocks', loadChildren: './salidastocks/salidastocks.module#SalidastocksModule',
        canActivateChild: [AuthGuard] },
    { path: 'salidastocks/ordentarea/:idordentarea', loadChildren: './salidastocks/salidastocks.module#SalidastocksModule'},
    { path: 'salidastocks/stock/:idstock', loadChildren: './salidastocks/salidastocks.module#SalidastocksModule'},
    { path: 'sexos', loadChildren: './sexos/sexos.module#SexosModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_modulos', loadChildren: './si_modulos/si_modulos.module#Si_modulosModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_permisos', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_permisos/si_modulo/:idsi_modulo', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule'},
    { path: 'si_permisos/si_rol/:idsi_rol', loadChildren: './si_permisos/si_permisos.module#Si_permisosModule'},
    { path: 'si_reportes', loadChildren: './si_reportes/si_reportes.module#Si_reportesModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_reportes/si_modulo/:idsi_modulo', loadChildren: './si_reportes/si_reportes.module#Si_reportesModule'},
    { path: 'si_rols', loadChildren: './si_rols/si_rols.module#Si_rolsModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_users', loadChildren: './si_users/si_users.module#Si_usersModule',
        canActivateChild: [AuthGuard] },
    { path: 'si_users/si_rol/:idsi_rol', loadChildren: './si_users/si_users.module#Si_usersModule'},
    { path: 'stocks', loadChildren: './stocks/stocks.module#StocksModule',
        canActivateChild: [AuthGuard] },
    { path: 'tareas', loadChildren: './tareas/tareas.module#TareasModule',
        canActivateChild: [AuthGuard] },
    { path: 'tareas/area/:idarea', loadChildren: './tareas/tareas.module#TareasModule'},
    { path: 'tareas/producto/:idproducto', loadChildren: './tareas/tareas.module#TareasModule'},
    { path: 'tipoalertas', loadChildren: './tipoalertas/tipoalertas.module#TipoalertasModule',
        canActivateChild: [AuthGuard] },
    { path: 'tipoprecios', loadChildren: './tipoprecios/tipoprecios.module#TipopreciosModule',
        canActivateChild: [AuthGuard] },
    ]
}
];
export const routing: ModuleWithProviders = RouterModule.forChild(routes);
